version: "3.8"

services:
    db:
        image: postgres:14-alpine
        restart: always
        environment:
            POSTGRES_USER: quicklist_user
            POSTGRES_PASSWORD: quicklist_password
            POSTGRES_DB: quicklist_db
        ports:
            - "5432:5432"
        volumes:
            - db_data:/var/lib/postgresql/data

volumes:
    db_data:
